server:
  port: 8080


spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/zhilulinghang?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ...
    password: ...
  application:
    name: backend

mybatis:
  configuration:
    map-underscore-to-camel-case: true